name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Build and Deploy to GCP Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/wgs-aayesha-sandbox/summit/aisummit25:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west1-docker.pkg.dev/wgs-aayesha-sandbox/summit/aisummit25:latest